// <auto-generated />
namespace POSSUM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class terminalID_in_Journal_log_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(terminalID_in_Journal_log_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201905061224111_terminalID_in_Journal_log_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
