//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSUM.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSSUM.Web.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        public static string AutoLogin {
            get {
                return ResourceManager.GetString("AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Limit.
        /// </summary>
        public static string BuyLimit {
            get {
                return ResourceManager.GetString("BuyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Back.
        /// </summary>
        public static string CashBack {
            get {
                return ResourceManager.GetString("CashBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        public static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        public static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlUnit.
        /// </summary>
        public static string ControlUnit {
            get {
                return ResourceManager.GetString("ControlUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No.
        /// </summary>
        public static string CustomerNo {
            get {
                return ResourceManager.GetString("CustomerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the selected record?.
        /// </summary>
        public static string DeleteConfMsg {
            get {
                return ResourceManager.GetString("DeleteConfMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string Deployment {
            get {
                return ResourceManager.GetString("Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Allowed.
        /// </summary>
        public static string DiscountAllowed {
            get {
                return ResourceManager.GetString("DiscountAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted Amount.
        /// </summary>
        public static string DiscountedAmount {
            get {
                return ResourceManager.GetString("DiscountedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy Report.
        /// </summary>
        public static string Discrepancy_Report {
            get {
                return ResourceManager.GetString("Discrepancy_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exl VAT.
        /// </summary>
        public static string Exl_Tax {
            get {
                return ResourceManager.GetString("Exl_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förväntat.
        /// </summary>
        public static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File.
        /// </summary>
        public static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        public static string Filterby {
            get {
                return ResourceManager.GetString("Filterby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten.
        /// </summary>
        public static string Forgotten {
            get {
                return ResourceManager.GetString("Forgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Product.
        /// </summary>
        public static string GroupProduct {
            get {
                return ResourceManager.GetString("GroupProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string Holder {
            get {
                return ResourceManager.GetString("Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Store.
        /// </summary>
        public static string IconStore {
            get {
                return ResourceManager.GetString("IconStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Note.
        /// </summary>
        public static string ImportantNote {
            get {
                return ResourceManager.GetString("ImportantNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Reference.
        /// </summary>
        public static string InvoiceReference {
            get {
                return ResourceManager.GetString("InvoiceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals.
        /// </summary>
        public static string Journals {
            get {
                return ResourceManager.GetString("Journals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string lblInventory {
            get {
                return ResourceManager.GetString("lblInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PANT Products.
        /// </summary>
        public static string lblPantProducts {
            get {
                return ResourceManager.GetString("lblPantProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string lblProducts {
            get {
                return ResourceManager.GetString("lblProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Margin:  SEK XXX        XX %.
        /// </summary>
        public static string MarginCalculation {
            get {
                return ResourceManager.GetString("MarginCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit.
        /// </summary>
        public static string NetProfit {
            get {
                return ResourceManager.GetString("NetProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string new1 {
            get {
                return ResourceManager.GetString("new1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Customer.
        /// </summary>
        public static string OpenCustomer {
            get {
                return ResourceManager.GetString("OpenCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Comment.
        /// </summary>
        public static string Order_Comment {
            get {
                return ResourceManager.GetString("Order_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org No.
        /// </summary>
        public static string OrgNo {
            get {
                return ResourceManager.GetString("OrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet.
        /// </summary>
        public static string Outlet {
            get {
                return ResourceManager.GetString("Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlets.
        /// </summary>
        public static string Outlets {
            get {
                return ResourceManager.GetString("Outlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over View.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pant Product.
        /// </summary>
        public static string PantProduct {
            get {
                return ResourceManager.GetString("PantProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Payment_Method_Account {
            get {
                return ResourceManager.GetString("Payment_Method_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Payment_Method_Cash {
            get {
                return ResourceManager.GetString("Payment_Method_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka.
        /// </summary>
        public static string Payment_Method_CashBack {
            get {
                return ResourceManager.GetString("Payment_Method_CashBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupong.
        /// </summary>
        public static string Payment_Method_Coupon {
            get {
                return ResourceManager.GetString("Payment_Method_Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string Payment_Method_CreditCard {
            get {
                return ResourceManager.GetString("Payment_Method_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Card.
        /// </summary>
        public static string Payment_Method_DebitCard {
            get {
                return ResourceManager.GetString("Payment_Method_DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Coupon.
        /// </summary>
        public static string Payment_Method_FreeCoupon {
            get {
                return ResourceManager.GetString("Payment_Method_FreeCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Card Terminal.
        /// </summary>
        public static string Payment_Method_Mobile {
            get {
                return ResourceManager.GetString("Payment_Method_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retur.
        /// </summary>
        public static string Payment_Method_Return {
            get {
                return ResourceManager.GetString("Payment_Method_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Receiver name.
        /// </summary>
        public static string PaymentReceiverName {
            get {
                return ResourceManager.GetString("PaymentReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Category.
        /// </summary>
        public static string PerCategory {
            get {
                return ResourceManager.GetString("PerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Day.
        /// </summary>
        public static string PerDay {
            get {
                return ResourceManager.GetString("PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hours.
        /// </summary>
        public static string PerHours {
            get {
                return ResourceManager.GetString("PerHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU.
        /// </summary>
        public static string PLU {
            get {
                return ResourceManager.GetString("PLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortCode.
        /// </summary>
        public static string PortCode {
            get {
                return ResourceManager.GetString("PortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal.
        /// </summary>
        public static string Postal {
            get {
                return ResourceManager.GetString("Postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation Time.
        /// </summary>
        public static string PreparationTime {
            get {
                return ResourceManager.GetString("PreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Category.
        /// </summary>
        public static string PrimaryCategory {
            get {
                return ResourceManager.GetString("PrimaryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product.
        /// </summary>
        public static string product1 {
            get {
                return ResourceManager.GetString("product1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit %.
        /// </summary>
        public static string ProfitPer {
            get {
                return ResourceManager.GetString("ProfitPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfitRates.
        /// </summary>
        public static string ProfitRates {
            get {
                return ResourceManager.GetString("ProfitRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Report.
        /// </summary>
        public static string ProfitReport {
            get {
                return ResourceManager.GetString("ProfitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for invoice.
        /// </summary>
        public static string ReadyOrder {
            get {
                return ResourceManager.GetString("ReadyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt#.
        /// </summary>
        public static string ReceiptNumber {
            get {
                return ResourceManager.GetString("ReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Report_Address {
            get {
                return ResourceManager.GetString("Report_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Added.
        /// </summary>
        public static string Report_CashAdded {
            get {
                return ResourceManager.GetString("Report_CashAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashdrawer opened.
        /// </summary>
        public static string Report_CashDrawerOpen {
            get {
                return ResourceManager.GetString("Report_CashDrawerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer open count.
        /// </summary>
        public static string Report_CashDrawerOpenCount {
            get {
                return ResourceManager.GetString("Report_CashDrawerOpenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Dropped.
        /// </summary>
        public static string Report_CashDropped {
            get {
                return ResourceManager.GetString("Report_CashDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier:.
        /// </summary>
        public static string Report_Cashier {
            get {
                return ResourceManager.GetString("Report_Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In.
        /// </summary>
        public static string Report_CashIn {
            get {
                return ResourceManager.GetString("Report_CashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Out.
        /// </summary>
        public static string Report_CashOut {
            get {
                return ResourceManager.GetString("Report_CashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Sum.
        /// </summary>
        public static string Report_CashSum {
            get {
                return ResourceManager.GetString("Report_CashSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale category.
        /// </summary>
        public static string Report_CategorySale {
            get {
                return ResourceManager.GetString("Report_CategorySale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Cat Count.
        /// </summary>
        public static string Report_CategorySaleCount {
            get {
                return ResourceManager.GetString("Report_CategorySaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Sales Count.
        /// </summary>
        public static string Report_CategorySaleCountHeading {
            get {
                return ResourceManager.GetString("Report_CategorySaleCountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Sales.
        /// </summary>
        public static string Report_CategorySaleHeading {
            get {
                return ResourceManager.GetString("Report_CategorySaleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed at.
        /// </summary>
        public static string Report_CloseDate {
            get {
                return ResourceManager.GetString("Report_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Report_Description {
            get {
                return ResourceManager.GetString("Report_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total discounts.
        /// </summary>
        public static string Report_DiscountCount {
            get {
                return ResourceManager.GetString("Report_DiscountCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END ORDER.
        /// </summary>
        public static string Report_EndOrder {
            get {
                return ResourceManager.GetString("Report_EndOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Report_From {
            get {
                return ResourceManager.GetString("Report_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string Report_GrandTotal {
            get {
                return ResourceManager.GetString("Report_GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand total net.
        /// </summary>
        public static string Report_GrandTotalNet {
            get {
                return ResourceManager.GetString("Report_GrandTotalNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand total return.
        /// </summary>
        public static string Report_GrandTotalReturn {
            get {
                return ResourceManager.GetString("Report_GrandTotalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand total sale.
        /// </summary>
        public static string Report_GrandTotalSale {
            get {
                return ResourceManager.GetString("Report_GrandTotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold count.
        /// </summary>
        public static string Report_HoldCount {
            get {
                return ResourceManager.GetString("Report_HoldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold total sale.
        /// </summary>
        public static string Report_HoldTotalSale {
            get {
                return ResourceManager.GetString("Report_HoldTotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened at.
        /// </summary>
        public static string Report_OpenDate {
            get {
                return ResourceManager.GetString("Report_OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order count.
        /// </summary>
        public static string Report_OrderCount {
            get {
                return ResourceManager.GetString("Report_OrderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org No:.
        /// </summary>
        public static string Report_OrgNo {
            get {
                return ResourceManager.GetString("Report_OrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other negative registrations.
        /// </summary>
        public static string Report_OtherNegativeRegistrations {
            get {
                return ResourceManager.GetString("Report_OtherNegativeRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Report_Payment {
            get {
                return ResourceManager.GetString("Report_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return payment.
        /// </summary>
        public static string Report_PaymentTypeReturn {
            get {
                return ResourceManager.GetString("Report_PaymentTypeReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType.
        /// </summary>
        public static string Report_PaymentTypeSale {
            get {
                return ResourceManager.GetString("Report_PaymentTypeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Report_Phone {
            get {
                return ResourceManager.GetString("Report_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        public static string Report_Printed {
            get {
                return ResourceManager.GetString("Report_Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Report_PrintedOf {
            get {
                return ResourceManager.GetString("Report_PrintedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale product count.
        /// </summary>
        public static string Report_ProductsCount {
            get {
                return ResourceManager.GetString("Report_ProductsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Report_Quantity {
            get {
                return ResourceManager.GetString("Report_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Report_ReceiptCopy {
            get {
                return ResourceManager.GetString("Report_ReceiptCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Amount.
        /// </summary>
        public static string Report_ReceiptCopyAmount {
            get {
                return ResourceManager.GetString("Report_ReceiptCopyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Count.
        /// </summary>
        public static string Report_ReceiptCopyCount {
            get {
                return ResourceManager.GetString("Report_ReceiptCopyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt count.
        /// </summary>
        public static string Report_ReceiptCount {
            get {
                return ResourceManager.GetString("Report_ReceiptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No:.
        /// </summary>
        public static string Report_ReceiptNo {
            get {
                return ResourceManager.GetString("Report_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Number.
        /// </summary>
        public static string Report_ReportNumber {
            get {
                return ResourceManager.GetString("Report_ReportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return count.
        /// </summary>
        public static string Report_ReturnCount {
            get {
                return ResourceManager.GetString("Report_ReturnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Return %.
        /// </summary>
        public static string Report_ReturnVATPercent {
            get {
                return ResourceManager.GetString("Report_ReturnVATPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Total Return.
        /// </summary>
        public static string Report_ReturnVATSum {
            get {
                return ResourceManager.GetString("Report_ReturnVATSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding.
        /// </summary>
        public static string Report_Rounding {
            get {
                return ResourceManager.GetString("Report_Rounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Report_Sale {
            get {
                return ResourceManager.GetString("Report_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Total.
        /// </summary>
        public static string Report_SaleTotal {
            get {
                return ResourceManager.GetString("Report_SaleTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale services count.
        /// </summary>
        public static string Report_ServicesCount {
            get {
                return ResourceManager.GetString("Report_ServicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Report_To {
            get {
                return ResourceManager.GetString("Report_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total net.
        /// </summary>
        public static string Report_TotalNet {
            get {
                return ResourceManager.GetString("Report_TotalNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total return.
        /// </summary>
        public static string Report_TotalReturn {
            get {
                return ResourceManager.GetString("Report_TotalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sale.
        /// </summary>
        public static string Report_TotalSale {
            get {
                return ResourceManager.GetString("Report_TotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string Report_Trainingmode {
            get {
                return ResourceManager.GetString("Report_Trainingmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale in training mode.
        /// </summary>
        public static string Report_TrainingModeCount {
            get {
                return ResourceManager.GetString("Report_TrainingModeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Id.
        /// </summary>
        public static string Report_UniqueIdentification {
            get {
                return ResourceManager.GetString("Report_UniqueIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string Report_VAT {
            get {
                return ResourceManager.GetString("Report_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT %.
        /// </summary>
        public static string Report_VATPercent {
            get {
                return ResourceManager.GetString("Report_VATPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT amount.
        /// </summary>
        public static string Report_VATSum {
            get {
                return ResourceManager.GetString("Report_VATSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generator.
        /// </summary>
        public static string Reportgenerator {
            get {
                return ResourceManager.GetString("Reportgenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportTag.
        /// </summary>
        public static string ReportTag {
            get {
                return ResourceManager.GetString("ReportTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to månad.
        /// </summary>
        public static string salemonth {
            get {
                return ResourceManager.GetString("salemonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        public static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Orders.
        /// </summary>
        public static string ScannerOrders {
            get {
                return ResourceManager.GetString("ScannerOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Button.
        /// </summary>
        public static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string SKU {
            get {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify.
        /// </summary>
        public static string Specify {
            get {
                return ResourceManager.GetString("Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky.
        /// </summary>
        public static string Sticky {
            get {
                return ResourceManager.GetString("Sticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock History Grouped.
        /// </summary>
        public static string StockHistoryGrouped {
            get {
                return ResourceManager.GetString("StockHistoryGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully.
        /// </summary>
        public static string successfully {
            get {
                return ResourceManager.GetString("successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Marginal.
        /// </summary>
        public static string Temp_Marginal {
            get {
                return ResourceManager.GetString("Temp Marginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Price.
        /// </summary>
        public static string Temp_Price {
            get {
                return ResourceManager.GetString("Temp Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Price End Date.
        /// </summary>
        public static string Temp_Price_End_Date {
            get {
                return ResourceManager.GetString("Temp Price End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Price Start Date.
        /// </summary>
        public static string Temp_Price_Start_Date {
            get {
                return ResourceManager.GetString("Temp Price Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string Terminals {
            get {
                return ResourceManager.GetString("Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Sheet.
        /// </summary>
        public static string TimeSheet {
            get {
                return ResourceManager.GetString("TimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s total sales.
        /// </summary>
        public static string TodaySaleTotal {
            get {
                return ResourceManager.GetString("TodaySaleTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Sold Product.
        /// </summary>
        public static string TopSoldProduct {
            get {
                return ResourceManager.GetString("TopSoldProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Return.
        /// </summary>
        public static string TotalReturn {
            get {
                return ResourceManager.GetString("TotalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sale.
        /// </summary>
        public static string TotalSale {
            get {
                return ResourceManager.GetString("TotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionReport.
        /// </summary>
        public static string TransactionReport {
            get {
                return ResourceManager.GetString("TransactionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under.
        /// </summary>
        public static string under {
            get {
                return ResourceManager.GetString("under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit In Pack.
        /// </summary>
        public static string UnitInPack {
            get {
                return ResourceManager.GetString("UnitInPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
